apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: list-pods-binding
  namespace: default
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-pods
subjects: 
  - 
#    apiGroup: rbac.authorization.k8s.io
    kind: ServiceAccount
    name: demo-sa
