apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    name: nginx
    internalVersion: 0.0.2
  name: kuard
spec:
  serviceAccountName: demo-sa
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
