kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-sample-rolebinding
subjects:
- kind: ServiceAccount
  name: rbac-sample-sa
roleRef:
  kind: Role
  name: rbac-sample-role
  apiGroup: rbac.authorization.k8s.io