apiVersion: v1
kind: Pod
metadata:
  labels:
    run: privileged
    name: privileged
    internalVersion: 0.0.1
  name: privileged
spec:
  volumes:
    - name: "root-data"
      hostPath:
        path: /
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: kuard
    resources:
      requests:
        cpu: "500m"
        memory: "1024i"
      limits:
        memory: "1024Mi"
    volumeMounts:
      - mountPath: "/data"
        name: "root-data"  
    securityContext:
      privileged: true
      procMount: UnmaskedProcMount
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
