apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: user1-busy
  name: user1-busy
spec:
  nodeSelector:
    run: "true"
  securityContext:
    runAsUser: 2001
    fsGroup: 3001
  containers:
  - command:
    - /bin/sh
    - -c 
    - "cat /security/creds && sleep 9999" 
    image: busybox
    name: user1-busy
    volumeMounts:
    - name:  secure-volume
      mountPath:  /security
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name:  secure-volume
    hostPath:
      path: /var/logs/security 
      
