apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  securityContext:
    runAsUser: 2001
  nodeSelector:
    run: "true"
  containers:
  - command:
    - /bin/sh
    - -c 
    - "sleep 9999" 
    image: pamir/privileged-escalation-image:0.0.1
    securityContext:
      allowPrivilegeEscalation: false
    imagePullPolicy: "Always"
    name: busy
  dnsPolicy: ClusterFirst
  restartPolicy: Never

      
