kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: marketing
  name: marketing-reader
rules:
- apiGroups: ["*"]
  resources: ["pods","services"]
  verbs: ["get","watch","list"]