kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: marketing-read-binding
  namespace: marketing
subjects:
- kind: User
  name: pamir
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: marketing-reader
  apiGroup: rbac.authorization.k8s.io